### ISSUE TITLE
Neoloader can't search subfile's all hashes

### ISSUE THREAD

**Issue by enOehTsIsihT** [DavidXanatos/NeoLoader#10]
clip0077.7z 1004 KB
https://mega.co.nz/#!M580TTyK!RRhFxTeV3tbFj0AvO8m6n0chH4zML3O-QvBBO5QPp7g

magnet:?xt=urn:btih:02E58F9D203DFB9DA4158C4D9925438439ADFCDE

**Comment by DavidXanatos** [comment]
fixed in build 153

**Comment by enOehTsIsihT** [comment]
It doesn't be fixed in build 153

magnet:?xt=urn:btih:02e58f9d203dfb9da4158c4d9925438439adfcde&xt=urn:neox:kUeW9-y9R6DE6xmhoS0pD-i8fUmARUxYGYR0aGVoHqA&dn=ubuntu-14.04.1&xl=3242197256

clip0084.7z 1.7 MB
https://mega.co.nz/#!lp0lALaQ!EXlittCjzjOEAd9o8asSC_ZTDMWjbo-qrnR6fYRsHfg

**Comment by DavidXanatos** [comment]
ach I see what I missed... will be fixed in next build for real I hope
