### ISSUE TITLE
hash bug

### ISSUE THREAD

**Issue by enOehTsIsihT** [DavidXanatos/NeoLoader#13]
clip0091.7z 778 KB
https://mega.co.nz/#!g4FUDK6B!D0wxeag10nHLcdelk4qg1czfoNJgAvIaTv-PZh7ppBE
NeoCoreLog_2015-04-30.7z 1.2 MB
https://mega.co.nz/#!t0cTxJ5R!BtxMKnWXGqytNjOSG2Lj61aCEOoVlmTlGLBjimhTpkw

magnet:?xt=urn:btih:e56f57f1d8ebc7d85fe34a2ebd844bab23d39e35
magnet:?xt=urn:btih:3b95cc9deb52439178fc1e162fda6c6004c01851

**Comment by DavidXanatos** [comment]
This is caused due to the order of the files in the torrent also having a influence on the neox hash, so it looks normal to me.
