### ISSUE TITLE
When closing neo from reay while a modal window is open neo crashes 

### ISSUE THREAD

**Issue by N30-** [DavidXanatos/NeoLoader#18]

**Comment by DavidXanatos** [comment]
Now, you cant close neo from tray if a modal window is open, simple yet effective solution

**Comment by enOehTsIsihT** [comment]
It doesn't be fixed.
clip0041.7z 520 KB
https://mega.co.nz/#!QgNjCC6T!Aa8MDlTsjkg-YwE888SOdTg_l460VEW4MUFcSz9Fk-E
NeoLoader v0.51_30.03.2015_18-57-54,427.dmp 60 KB
https://mega.co.nz/#!c9FWnaLI!-WGD7aad07RhfqG5AXm83hymdzzPSE2_NbxJ-vtxRNo

**Comment by DavidXanatos** [comment]
fix uploaded
