### ISSUE TITLE
Filters for QFileDialog inside the Add Torrent/Container window

### ISSUE THREAD

**Issue by vincenzo-petronio** [DavidXanatos/NeoLoader#8]
_Incomplete eMule Download_ is missing from _All Supported Files_ item :blush:

![neoloader_all_supported_files](https://cloud.githubusercontent.com/assets/4283382/7095309/601ae506-dfc9-11e4-93d4-a2b68221655b.png)

**Comment by DavidXanatos** [comment]
ok,
fixed in next release
